### ISSUE TITLE
데이터베이스 User 스키마 설계

### ISSUE THREAD

**Issue by woo-cher** [gnu-runtime/viser#7]
- <USER> 스키마 구현하기

![image](https://cloud.githubusercontent.com/assets/13360519/24714277/ff8e46a2-1a62-11e7-9db6-c32f18fbfd4b.png)

https://trello-attachments.s3.amazonaws.com/5753b11d915ba4f88ab05c7d/587f9bbfb643bbb4ec8a9422/89b2606aec23608af2ba3ba1f3a0af41/sign-up.jsp.png

**Comment by Choidandy** [comment]
https://trello-attachments.s3.amazonaws.com/5753b11d915ba4f88ab05c7d/587f9bbfb643bbb4ec8a9422/89b2606aec23608af2ba3ba1f3a0af41/sign-up.jsp.png

**Comment by flzl2008** [comment]
구현완료
